from enum import Enum

class TextType(Enum):
    WELCOME = "SELAMAT DATANG"
    VEHICLE_DETECTED = "KENDARAAN TERDETEKSI"
    CARD_TAP_REQUEST = "SILAKAN TAP KARTU"
    CARD_READ_NOTIFY = "KARTU TERBACA"
    UNDEFINED = ""
